# Generated by Django 5.2.4 on 2025-08-18 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="banner_transition_time",
            field=models.PositiveIntegerField(
                default=5,
                help_text="메인 배너가 자동으로 넘어가는 시간 (1-30초)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
                verbose_name="배너 전환 시간 (초)",
            ),
        ),
    ]
