# Generated by Django 5.2.4 on 2025-07-23 00:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("CUSTOMER", "고객"),
                            ("STAFF", "직원"),
                            ("ADMIN", "관리자"),
                        ],
                        default="CUSTOMER",
                        max_length=10,
                        verbose_name="사용자 타입",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="전화번호"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="생년월일"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "남성"), ("F", "여성"), ("O", "기타")],
                        max_length=1,
                        null=True,
                        verbose_name="성별",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="우편번호"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="주소"
                    ),
                ),
                (
                    "detail_address",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="상세주소"
                    ),
                ),
                (
                    "is_email_verified",
                    models.BooleanField(default=False, verbose_name="이메일 인증 여부"),
                ),
                (
                    "is_phone_verified",
                    models.BooleanField(
                        default=False, verbose_name="전화번호 인증 여부"
                    ),
                ),
                (
                    "marketing_agreed",
                    models.BooleanField(default=False, verbose_name="마케팅 수신 동의"),
                ),
                (
                    "terms_agreed",
                    models.BooleanField(default=False, verbose_name="이용약관 동의"),
                ),
                (
                    "privacy_agreed",
                    models.BooleanField(
                        default=False, verbose_name="개인정보처리방침 동의"
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profiles/",
                        verbose_name="프로필 이미지",
                    ),
                ),
                ("memo", models.TextField(blank=True, null=True, verbose_name="메모")),
                (
                    "total_purchase_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="총 구매 금액",
                    ),
                ),
                (
                    "purchase_count",
                    models.PositiveIntegerField(default=0, verbose_name="구매 횟수"),
                ),
                (
                    "last_purchase_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="마지막 구매일"
                    ),
                ),
                (
                    "points",
                    models.PositiveIntegerField(default=0, verbose_name="포인트"),
                ),
                (
                    "membership_level",
                    models.CharField(
                        choices=[
                            ("BRONZE", "브론즈"),
                            ("SILVER", "실버"),
                            ("GOLD", "골드"),
                            ("PLATINUM", "플래티넘"),
                            ("DIAMOND", "다이아몬드"),
                        ],
                        default="BRONZE",
                        max_length=10,
                        verbose_name="회원 등급",
                    ),
                ),
                (
                    "admin_level",
                    models.IntegerField(
                        choices=[
                            (0, "권한 없음"),
                            (1, "읽기 전용"),
                            (2, "일반 관리자"),
                            (3, "중간 관리자"),
                            (4, "상위 관리자"),
                            (5, "최고 관리자"),
                        ],
                        default=0,
                        help_text="관리자 타입 사용자에게만 적용됩니다.",
                        verbose_name="관리자 권한 레벨",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="가입일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "withdrawal_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="탈퇴일"),
                ),
                (
                    "withdrawal_reason",
                    models.TextField(blank=True, null=True, verbose_name="탈퇴 사유"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자",
                "db_table": "users",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PointHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "point_type",
                    models.CharField(
                        choices=[
                            ("EARN", "적립"),
                            ("USE", "사용"),
                            ("EXPIRE", "소멸"),
                            ("CANCEL", "취소"),
                        ],
                        max_length=10,
                        verbose_name="포인트 타입",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="포인트 금액")),
                ("balance", models.IntegerField(verbose_name="잔액")),
                ("description", models.CharField(max_length=200, verbose_name="설명")),
                (
                    "order_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="주문 번호"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "expire_date",
                    models.DateField(blank=True, null=True, verbose_name="만료일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "포인트 내역",
                "verbose_name_plural": "포인트 내역",
                "db_table": "point_histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShippingAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(max_length=50, verbose_name="배송지 별칭"),
                ),
                (
                    "recipient_name",
                    models.CharField(max_length=50, verbose_name="수령인 이름"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="전화번호"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="우편번호"),
                ),
                ("address", models.CharField(max_length=200, verbose_name="주소")),
                (
                    "detail_address",
                    models.CharField(max_length=200, verbose_name="상세주소"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본 배송지"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "배송지",
                "verbose_name_plural": "배송지",
                "db_table": "shipping_addresses",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("user_view", "사용자 조회"),
                            ("user_create", "사용자 생성"),
                            ("user_edit", "사용자 수정"),
                            ("user_delete", "사용자 삭제"),
                            ("user_permission", "사용자 권한 관리"),
                            ("product_view", "상품 조회"),
                            ("product_create", "상품 생성"),
                            ("product_edit", "상품 수정"),
                            ("product_delete", "상품 삭제"),
                            ("product_price", "상품 가격 관리"),
                            ("order_view", "주문 조회"),
                            ("order_edit", "주문 수정"),
                            ("order_cancel", "주문 취소"),
                            ("order_refund", "환불 처리"),
                            ("inventory_view", "재고 조회"),
                            ("inventory_edit", "재고 수정"),
                            ("inventory_move", "재고 이동"),
                            ("report_view", "보고서 조회"),
                            ("report_create", "보고서 생성"),
                            ("report_export", "보고서 내보내기"),
                            ("report_schedule", "보고서 스케줄 관리"),
                            ("platform_view", "플랫폼 조회"),
                            ("platform_manage", "플랫폼 관리"),
                            ("platform_sync", "플랫폼 동기화"),
                            ("system_view", "시스템 설정 조회"),
                            ("system_config", "시스템 설정 변경"),
                            ("system_backup", "시스템 백업"),
                            ("financial_view", "재무 조회"),
                            ("financial_manage", "재무 관리"),
                            ("financial_export", "재무 데이터 내보내기"),
                        ],
                        max_length=50,
                        verbose_name="권한",
                    ),
                ),
                (
                    "granted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="권한 부여일"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="비어있으면 무기한",
                        null=True,
                        verbose_name="권한 만료일",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 상태"),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="권한 부여자",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 권한",
                "verbose_name_plural": "사용자 권한",
                "db_table": "user_permissions",
                "ordering": ["user", "permission"],
                "unique_together": {("user", "permission")},
            },
        ),
    ]
