# Generated by Django 5.2.4 on 2025-07-21 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_level',
            field=models.IntegerField(choices=[(0, '권한 없음'), (1, '읽기 전용'), (2, '일반 관리자'), (3, '중간 관리자'), (4, '상위 관리자'), (5, '최고 관리자')], default=0, help_text='관리자 타입 사용자에게만 적용됩니다.', verbose_name='관리자 권한 레벨'),
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('user_view', '사용자 조회'), ('user_create', '사용자 생성'), ('user_edit', '사용자 수정'), ('user_delete', '사용자 삭제'), ('user_permission', '사용자 권한 관리'), ('product_view', '상품 조회'), ('product_create', '상품 생성'), ('product_edit', '상품 수정'), ('product_delete', '상품 삭제'), ('product_price', '상품 가격 관리'), ('order_view', '주문 조회'), ('order_edit', '주문 수정'), ('order_cancel', '주문 취소'), ('order_refund', '환불 처리'), ('inventory_view', '재고 조회'), ('inventory_edit', '재고 수정'), ('inventory_move', '재고 이동'), ('report_view', '보고서 조회'), ('report_create', '보고서 생성'), ('report_export', '보고서 내보내기'), ('report_schedule', '보고서 스케줄 관리'), ('platform_view', '플랫폼 조회'), ('platform_manage', '플랫폼 관리'), ('platform_sync', '플랫폼 동기화'), ('system_view', '시스템 설정 조회'), ('system_config', '시스템 설정 변경'), ('system_backup', '시스템 백업'), ('financial_view', '재무 조회'), ('financial_manage', '재무 관리'), ('financial_export', '재무 데이터 내보내기')], max_length=50, verbose_name='권한')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='권한 부여일')),
                ('expires_at', models.DateTimeField(blank=True, help_text='비어있으면 무기한', null=True, verbose_name='권한 만료일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='권한 부여자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 권한',
                'verbose_name_plural': '사용자 권한',
                'db_table': 'user_permissions',
                'ordering': ['user', 'permission'],
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
