# Generated by Django 4.2.7 on 2025-06-29 12:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("platforms", "0001_initial"),
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("IN", "입고"),
                            ("OUT", "출고"),
                            ("ADJUST", "조정"),
                            ("TRANSFER", "이동"),
                            ("RETURN", "반품"),
                            ("DAMAGE", "손상"),
                            ("SALE", "판매"),
                            ("PURCHASE", "구매"),
                            ("CANCEL", "취소"),
                            ("CORRECTION", "수정"),
                        ],
                        max_length=20,
                        verbose_name="이동 유형",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="수량",
                    ),
                ),
                (
                    "previous_stock",
                    models.IntegerField(default=0, verbose_name="이전 재고"),
                ),
                ("current_stock", models.IntegerField(default=0, verbose_name="현재 재고")),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, verbose_name="참조 번호"),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=200, verbose_name="사유"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="메모")),
                (
                    "warehouse",
                    models.CharField(blank=True, max_length=100, verbose_name="창고"),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="단위 원가",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="총 원가",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "is_automated",
                    models.BooleanField(default=False, verbose_name="자동 처리"),
                ),
                (
                    "source_system",
                    models.CharField(blank=True, max_length=50, verbose_name="소스 시스템"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.order",
                        verbose_name="관련 주문",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="platforms.platform",
                        verbose_name="플랫폼",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="products.product",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "재고 이동",
                "verbose_name_plural": "재고 이동",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "-created_at"],
                        name="inventory_s_product_cfb4fb_idx",
                    ),
                    models.Index(
                        fields=["movement_type", "-created_at"],
                        name="inventory_s_movemen_a71f62_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="inventory_s_created_05ebf5_idx"
                    ),
                    models.Index(
                        fields=["reference_number"],
                        name="inventory_s_referen_79719e_idx",
                    ),
                    models.Index(
                        fields=["order"], name="inventory_s_order_i_e9e6e3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_stock_level",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="최소 재고",
                    ),
                ),
                (
                    "max_stock_level",
                    models.IntegerField(
                        default=1000,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="최대 재고",
                    ),
                ),
                (
                    "reorder_point",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="재주문 시점",
                    ),
                ),
                (
                    "reorder_quantity",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="재주문 수량",
                    ),
                ),
                (
                    "safety_stock",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="안전 재고",
                    ),
                ),
                (
                    "warehouse",
                    models.CharField(
                        blank=True, default="DEFAULT", max_length=100, verbose_name="창고"
                    ),
                ),
                (
                    "auto_reorder_enabled",
                    models.BooleanField(default=False, verbose_name="자동 재주문 활성화"),
                ),
                (
                    "lead_time_days",
                    models.IntegerField(
                        default=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="리드타임(일)",
                    ),
                ),
                (
                    "is_seasonal",
                    models.BooleanField(default=False, verbose_name="계절성 상품"),
                ),
                (
                    "seasonal_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=5,
                        verbose_name="계절성 계수",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_level",
                        to="products.product",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "재고 수준",
                "verbose_name_plural": "재고 수준",
                "indexes": [
                    models.Index(
                        fields=["product"], name="inventory_s_product_6a96cf_idx"
                    ),
                    models.Index(
                        fields=["warehouse"], name="inventory_s_warehou_152f92_idx"
                    ),
                    models.Index(
                        fields=["auto_reorder_enabled"],
                        name="inventory_s_auto_re_9ec75c_idx",
                    ),
                ],
                "unique_together": {("product", "warehouse")},
            },
        ),
        migrations.CreateModel(
            name="StockAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("LOW_STOCK", "재고 부족"),
                            ("OUT_OF_STOCK", "재고 없음"),
                            ("OVERSTOCK", "재고 과다"),
                            ("EXPIRY_WARNING", "유통기한 임박"),
                            ("SLOW_MOVING", "장기 재고"),
                        ],
                        max_length=20,
                        verbose_name="알림 유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "활성"),
                            ("RESOLVED", "해결됨"),
                            ("DISMISSED", "무시됨"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("message", models.TextField(verbose_name="알림 메시지")),
                (
                    "threshold_value",
                    models.IntegerField(blank=True, null=True, verbose_name="임계값"),
                ),
                (
                    "current_value",
                    models.IntegerField(blank=True, null=True, verbose_name="현재값"),
                ),
                (
                    "is_email_sent",
                    models.BooleanField(default=False, verbose_name="이메일 발송됨"),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="이메일 발송일시"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="해결일시"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_alerts",
                        to="products.product",
                        verbose_name="상품",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="해결자",
                    ),
                ),
            ],
            options={
                "verbose_name": "재고 알림",
                "verbose_name_plural": "재고 알림",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "status"],
                        name="inventory_s_product_53464e_idx",
                    ),
                    models.Index(
                        fields=["alert_type", "status"],
                        name="inventory_s_alert_t_938177_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="inventory_s_status_81ea13_idx",
                    ),
                ],
                "unique_together": {("product", "alert_type", "status")},
            },
        ),
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="트랜잭션 번호"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("ADJUSTMENT", "재고 조정"),
                            ("TRANSFER", "창고 이동"),
                            ("STOCKTAKE", "재고 실사"),
                            ("BULK_UPDATE", "일괄 업데이트"),
                            ("PLATFORM_SYNC", "플랫폼 동기화"),
                        ],
                        max_length=20,
                        verbose_name="트랜잭션 유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기중"),
                            ("PROCESSING", "처리중"),
                            ("COMPLETED", "완료"),
                            ("FAILED", "실패"),
                            ("CANCELLED", "취소"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("total_items", models.IntegerField(default=0, verbose_name="총 항목 수")),
                (
                    "processed_items",
                    models.IntegerField(default=0, verbose_name="처리된 항목 수"),
                ),
                (
                    "failed_items",
                    models.IntegerField(default=0, verbose_name="실패한 항목 수"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="시작일시"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="완료일시"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="메타데이터"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "재고 트랜잭션",
                "verbose_name_plural": "재고 트랜잭션",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="inventory_i_status_dc042b_idx",
                    ),
                    models.Index(
                        fields=["transaction_type"],
                        name="inventory_i_transac_2eccee_idx",
                    ),
                    models.Index(
                        fields=["created_by"], name="inventory_i_created_734211_idx"
                    ),
                ],
            },
        ),
    ]
