# Generated by Django 4.2.7 on 2025-07-02 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("INVENTORY", "재고 보고서"),
                            ("SALES", "판매 보고서"),
                            ("FINANCIAL", "재무 보고서"),
                            ("PERFORMANCE", "성과 보고서"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "일간"),
                            ("WEEKLY", "주간"),
                            ("MONTHLY", "월간"),
                            ("QUARTERLY", "분기별"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recipients", models.JSONField(default=list, verbose_name="수신자 목록")),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "last_generated",
                    models.DateTimeField(blank=True, null=True, verbose_name="최근 생성일"),
                ),
                (
                    "next_generation",
                    models.DateTimeField(blank=True, null=True, verbose_name="다음 생성일"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="보고서 제목")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("INVENTORY", "재고 보고서"),
                            ("SALES", "판매 보고서"),
                            ("FINANCIAL", "재무 보고서"),
                            ("PERFORMANCE", "성과 보고서"),
                        ],
                        max_length=20,
                        verbose_name="보고서 유형",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "is_scheduled",
                    models.BooleanField(default=False, verbose_name="정기 생성"),
                ),
                (
                    "schedule_frequency",
                    models.CharField(blank=True, max_length=20, verbose_name="생성 주기"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "보고서",
                "verbose_name_plural": "보고서",
                "ordering": ["-created_at"],
            },
        ),
    ]
