# Generated by Django 4.2.7 on 2025-07-05 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.UUIDField(
                        default=uuid.uuid4, unique=True, verbose_name="보고서 ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="새 보고서", max_length=200, verbose_name="제목"
                    ),
                ),
                ("period_start", models.DateTimeField(verbose_name="시작일")),
                ("period_end", models.DateTimeField(verbose_name="종료일")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기중"),
                            ("GENERATING", "생성중"),
                            ("COMPLETED", "완료"),
                            ("FAILED", "실패"),
                            ("EXPIRED", "만료"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("HTML", "HTML"),
                            ("PDF", "PDF"),
                            ("EXCEL", "Excel"),
                            ("CSV", "CSV"),
                            ("JSON", "JSON"),
                        ],
                        default="HTML",
                        max_length=10,
                        verbose_name="형식",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(blank=True, max_length=500, verbose_name="파일 경로"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="파일 크기(bytes)"
                    ),
                ),
                ("data", models.JSONField(default=dict, verbose_name="보고서 데이터")),
                ("summary", models.JSONField(default=dict, verbose_name="요약 정보")),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="만료일"),
                ),
                (
                    "generation_time",
                    models.FloatField(blank=True, null=True, verbose_name="생성 시간(초)"),
                ),
                (
                    "row_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="데이터 행 수"
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "생성된 보고서",
                "verbose_name_plural": "생성된 보고서",
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("VIEW", "조회"),
                            ("DOWNLOAD", "다운로드"),
                            ("SHARE", "공유"),
                            ("DELETE", "삭제"),
                        ],
                        max_length=20,
                        verbose_name="액션",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP 주소"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "accessed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="접근일"),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reports.generatedreport",
                        verbose_name="보고서",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "보고서 접근 로그",
                "verbose_name_plural": "보고서 접근 로그",
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="새 북마크",
                        max_length=100,
                        verbose_name="북마크 이름",
                    ),
                ),
                ("configuration", models.JSONField(default=dict, verbose_name="설정")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
            ],
            options={
                "verbose_name": "보고서 북마크",
                "verbose_name_plural": "보고서 북마크",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="새 보고서 템플릿", max_length=100, verbose_name="템플릿 이름"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="보고서 템플릿에 대한 설명을 입력하세요.", verbose_name="설명"
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("INVENTORY", "재고 보고서"),
                            ("SALES", "매출 보고서"),
                            ("FINANCIAL", "재무 보고서"),
                            ("PLATFORM", "플랫폼 보고서"),
                            ("PRODUCT", "상품 보고서"),
                            ("ORDER", "주문 보고서"),
                            ("CUSTOM", "사용자 정의"),
                        ],
                        default="INVENTORY",
                        max_length=20,
                        verbose_name="보고서 유형",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "일간"),
                            ("WEEKLY", "주간"),
                            ("MONTHLY", "월간"),
                            ("QUARTERLY", "분기"),
                            ("YEARLY", "연간"),
                            ("ON_DEMAND", "수동"),
                        ],
                        default="ON_DEMAND",
                        max_length=20,
                        verbose_name="생성 주기",
                    ),
                ),
                ("configuration", models.JSONField(default=dict, verbose_name="설정")),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=True, null=True, verbose_name="활성 상태"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="공개 여부"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="생성일"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="수정일"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "보고서 템플릿",
                "verbose_name_plural": "보고서 템플릿",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="reportschedule",
            options={
                "ordering": ["next_run"],
                "verbose_name": "보고서 스케줄",
                "verbose_name_plural": "보고서 스케줄",
            },
        ),
        migrations.RemoveField(
            model_name="reportschedule",
            name="frequency",
        ),
        migrations.RemoveField(
            model_name="reportschedule",
            name="last_generated",
        ),
        migrations.RemoveField(
            model_name="reportschedule",
            name="next_generation",
        ),
        migrations.RemoveField(
            model_name="reportschedule",
            name="recipients",
        ),
        migrations.RemoveField(
            model_name="reportschedule",
            name="report_type",
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="생성일"
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="생성자",
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="cron_expression",
            field=models.CharField(blank=True, max_length=100, verbose_name="Cron 표현식"),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="email_recipients",
            field=models.JSONField(default=list, verbose_name="이메일 수신자"),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="interval_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="간격(일)"
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="last_run",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="마지막 실행일",
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="name",
            field=models.CharField(
                default="새 보고서 스케줄", max_length=100, verbose_name="스케줄 이름"
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="next_run",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="다음 실행일"
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="schedule_type",
            field=models.CharField(
                choices=[
                    ("CRON", "Cron 표현식"),
                    ("INTERVAL", "간격"),
                    ("CALENDAR", "달력 기반"),
                ],
                default="INTERVAL",
                max_length=20,
                verbose_name="스케줄 유형",
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="수정일"),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="활성 상태"),
        ),
        migrations.DeleteModel(
            name="Report",
        ),
        migrations.AddField(
            model_name="reportbookmark",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reports.reporttemplate",
                verbose_name="템플릿",
            ),
        ),
        migrations.AddField(
            model_name="reportbookmark",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AddField(
            model_name="generatedreport",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reports.reporttemplate",
                verbose_name="템플릿",
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reports.reporttemplate",
                verbose_name="템플릿",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reportbookmark",
            unique_together={("user", "template")},
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(
                fields=["status", "generated_at"], name="reports_gen_status_4d1741_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="generatedreport",
            index=models.Index(
                fields=["template", "period_start"],
                name="reports_gen_templat_376e66_idx",
            ),
        ),
    ]
