# Generated by Django 5.2.4 on 2025-08-18 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("shop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MainBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="배너 제목")),
                (
                    "subtitle",
                    models.CharField(blank=True, max_length=200, verbose_name="부제목"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="banners/", verbose_name="배너 이미지"),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="클릭 시 이동할 URL",
                        verbose_name="링크 URL",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        default="자세히 보기", max_length=50, verbose_name="버튼 텍스트"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="낮은 숫자가 먼저 표시됩니다",
                        verbose_name="순서",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
            ],
            options={
                "verbose_name": "메인 배너",
                "verbose_name_plural": "메인 배너",
                "db_table": "shop_main_banners",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeaturedProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="낮은 숫자가 먼저 표시됩니다",
                        verbose_name="순서",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_items",
                        to="products.product",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "추천 상품",
                "verbose_name_plural": "추천 상품",
                "db_table": "shop_featured_products",
                "ordering": ["order", "-created_at"],
                "unique_together": {("product",)},
            },
        ),
    ]
