# Generated by Django 4.2.7 on 2025-07-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platforms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="platform",
            name="api_endpoint",
            field=models.URLField(blank=True, null=True, verbose_name="API 엔드포인트"),
        ),
        migrations.AddField(
            model_name="platform",
            name="description",
            field=models.TextField(blank=True, verbose_name="설명"),
        ),
        migrations.AddField(
            model_name="platform",
            name="last_sync_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="마지막 동기화 시간"
            ),
        ),
        migrations.AddField(
            model_name="platform",
            name="last_sync_message",
            field=models.TextField(blank=True, verbose_name="마지막 동기화 메시지"),
        ),
        migrations.AddField(
            model_name="platform",
            name="last_sync_status",
            field=models.CharField(
                blank=True,
                choices=[("success", "성공"), ("error", "오류"), ("running", "진행중")],
                max_length=20,
                null=True,
                verbose_name="마지막 동기화 상태",
            ),
        ),
        migrations.AddField(
            model_name="platform",
            name="sync_enabled",
            field=models.BooleanField(default=False, verbose_name="동기화 활성화"),
        ),
        migrations.AddField(
            model_name="platform",
            name="sync_interval",
            field=models.IntegerField(default=60, verbose_name="동기화 간격(분)"),
        ),
    ]
