# Generated by Django 4.2.7 on 2025-06-29 12:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("platforms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(max_length=50, unique=True, verbose_name="주문번호"),
                ),
                (
                    "platform_order_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="플랫폼 주문 ID"
                    ),
                ),
                ("customer_name", models.CharField(max_length=100, verbose_name="고객명")),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="고객 이메일"
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="고객 전화번호"),
                ),
                ("shipping_address", models.TextField(verbose_name="배송 주소")),
                (
                    "shipping_zipcode",
                    models.CharField(max_length=10, verbose_name="우편번호"),
                ),
                (
                    "shipping_method",
                    models.CharField(blank=True, max_length=100, verbose_name="배송방법"),
                ),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=100, verbose_name="송장번호"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기중"),
                            ("CONFIRMED", "확인됨"),
                            ("PROCESSING", "처리중"),
                            ("SHIPPED", "배송중"),
                            ("DELIVERED", "배송완료"),
                            ("CANCELLED", "취소됨"),
                            ("REFUNDED", "환불됨"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="총 금액"
                    ),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="배송비"
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="할인 금액"
                    ),
                ),
                ("order_date", models.DateTimeField(verbose_name="주문일시")),
                (
                    "shipped_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="배송일시"),
                ),
                (
                    "delivered_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="배송완료일시"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="메모")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="platforms.platform",
                        verbose_name="플랫폼",
                    ),
                ),
            ],
            options={
                "verbose_name": "주문",
                "verbose_name_plural": "주문",
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="수량",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="단가"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="총 금액"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="주문",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="상품",
                    ),
                ),
            ],
            options={
                "verbose_name": "주문 상품",
                "verbose_name_plural": "주문 상품",
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["platform", "status"], name="orders_orde_platfor_efd461_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["order_date"], name="orders_orde_order_d_d71205_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="orders_orde_status_c6dd84_idx"),
        ),
    ]
