# Generated by Django 4.2.7 on 2025-07-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancelled_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="취소일시"),
        ),
        migrations.AddField(
            model_name="order",
            name="refunded_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="환불일시"),
        ),
    ]
