# Generated by Django 4.2.7 on 2025-06-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text='예: "fas fa-mobile-alt"',
                max_length=50,
                verbose_name="아이콘 클래스",
            ),
        ),
    ]
