# Generated by Django 4.2.7 on 2025-07-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_category_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="code",
            field=models.CharField(
                blank=True, max_length=20, unique=True, verbose_name="카테고리 코드"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.CharField(
                default="fas fa-folder",
                help_text="FontAwesome 아이콘 클래스를 입력하세요",
                max_length=50,
                verbose_name="아이콘",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["code"], name="products_ca_code_b044cd_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["is_active"], name="products_ca_is_acti_a2d000_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["parent"], name="products_ca_parent__f3c24e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["sort_order"], name="products_ca_sort_or_c50e68_idx"
            ),
        ),
    ]
